language: c

compiler:
  - gcc

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qy postgresql-server-dev-9.4

script:
  - make
  - sudo make install
  - PGUSER=postgres make installcheck || { cat regression.diffs; false; }
